# Generated by Django 4.2.4 on 2023-08-14 18:54

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=gallery.models.image_upload)),
                ('description', models.TextField(max_length=5000)),
            ],
        ),
    ]
